drop table incidents if exists;
create table incidents (
    id bigint generated by default as identity,
    description varchar(255),
    deadline timestamp,
    status varchar(255),
    severity varchar(255),
    created timestamp,
    created_by varchar(255),
    assigned_to varchar(255),
    primary key (id)
);

insert into incidents(id, description, status, severity, created, created_by) values (1, 'Engine stopped working', 'SUBMITTED', 'MAJOR', '2012-04-24 10:00:05', 'ACME Factory');